# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Keep Alive

on:
  schedule:
    - cron: '*/600 * * * *'

permissions:
  contents: read

jobs:
  keep_alive:
    runs-on: ubuntu-latest
    steps:
    - name: Send request to keep the app alive
      run: curl -sS https://yandexmaster-bxajbknwwrn5gqtuy8gqhw.streamlit.app
